"""short_url

Revision ID: 96644b538459
Revises: b881040fa79d
Create Date: 2025-05-31 17:24:07.972640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96644b538459'
down_revision: Union[str, None] = 'b881040fa79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.alter_column('note', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.create_table('images',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('note_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name=op.f('images_note_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('images_pkey'))
    )
    # ### end Alembic commands ###
